# Generated by Django 3.2.16 on 2023-02-09 17:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Consultation', 'Consultation'), ('Details & Design', 'Details & Design'), ('Fabrics', 'Fabrics'), ('First Fitting', 'First Fitting'), ('Second Fitting', 'Second Fitting'), ('Pick-up', 'Pick-up')], default='Consultation', max_length=25)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(choices=[('8:30 AM', '8:30 AM'), ('11:30 AM', '11:30 AM'), ('4:00 PM', '4:00 PM'), ('5:00 PM', '5:00 PM'), ('6:00 PM', '6:00 PM')], default='8:30 AM', max_length=10)),
                ('comments', models.TextField()),
                ('submitted', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submitted'],
            },
        ),
    ]
