# Generated by Django 3.2.16 on 2023-01-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20230128_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['submitted']},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='datetime_submit',
            new_name='submitted',
        ),
    ]
